import MainComponent from 'components/shared/MainComponent'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from './styles.module.css'

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <MainComponent>
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => router.push('/Auth/Login')}>Login</button>
    </div>
    </MainComponent>
  )
}

export default Home
